In [1]:
#1

import numpy as np
x=np.ones((7,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
#2

n=5
for i in range(1,n+1):
    for j in range(1,i+1):
      print(j,end=" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [5]:
#3

import  numpy as np
int_0_to_100=np.arange(101)
print(int_0_to_100)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [7]:
#4

number=int(input("Enter a number: "))
total_sum=sum(range(1,number+1))
print(f"The sum of all numbers from 1 to {number} is {total_sum}.")

Enter a number:  10


The sum of all numbers from 1 to 10 is 55.


In [9]:
#5

import numpy as np
array=np.arange(100,200,10).reshape(5,2)
print(array)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
