In [20]:
#11

import numpy as np
a = np.random.randint(1, 51, size = (3, 4))
print(a)
print("Mean: ", np.mean(a), "\nMedian: ", np.median(a), "\nStandard Deviation: ", np.std(a))
c = 0
s = [0]
for i in range(3):
    s.append(0)
    for j in a[i]:
        s[i] += j
    c += s[i]
for i in range(3):
    print("The sum of ", i, " row is ", s[i])
print("The total sum is ", c)
a = np.reshape(a, (2, 6))
print(a)

[[ 4 12 48 27]
 [25 45  1  9]
 [34 49 50 49]]
Mean:  29.416666666666668 
Median:  30.5 
Standard Deviation:  18.254946057317056
The sum of  0  row is  91
The sum of  1  row is  80
The sum of  2  row is  182
The total sum is  353
[[ 4 12 48 27 25 45]
 [ 1  9 34 49 50 49]]


In [26]:
#12

import numpy as np
a = np.random.randint(1, 51, size = (3, 3))
print("a:\n", a)
b = np.random.randint(1, 51, size = (3, 3))
print("b:\n", b)
print("The sum is: ", a + b)
print("The product is: ", a * b)
print("The difference is: ", a - b)
print("The transpose is: ", np.linalg.det(a), "\n", np.linalg.det(b))
if(np.linalg.det(a) != 0):
    print("Inverse of a is: \n", np.transpose(a) / np.linalg.det(a))
if(np.linalg.det(b) != 0):
    print("Inverse of a is: \n", np.transpose(b) / np.linalg.det(b))

a:
 [[18 10 24]
 [12  1 29]
 [46  3 47]]
b:
 [[40 34 44]
 [17 25 45]
 [37 49 16]]
The sum is:  [[58 44 68]
 [29 26 74]
 [83 52 63]]
The product is:  [[ 720  340 1056]
 [ 204   25 1305]
 [1702  147  752]]
The difference is:  [[-22 -24 -20]
 [ -5 -24 -16]
 [  9 -46  31]]
The transpose is:  6740.000000000007 
 -28885.999999999975
Inverse of a is: 
 [[0.00267062 0.00178042 0.00682493]
 [0.00148368 0.00014837 0.0004451 ]
 [0.00356083 0.00430267 0.00697329]]
Inverse of a is: 
 [[-0.00138475 -0.00058852 -0.0012809 ]
 [-0.00117704 -0.00086547 -0.00169632]
 [-0.00152323 -0.00155785 -0.0005539 ]]


In [30]:
#13
import numpy as np

In [80]:
#a

vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [82]:
#b

vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [84]:
#c

vector = np.random.randint(100, 490, size = 10)
print(vector)

[154 443 254 237 278 479 309 368 359 308]


In [86]:
#d

vector = np.random.randint(0, 51, size = 10)
reverse = np.flip(vector)
print(reverse)

[31 44 10 25 29 19 46 11 19 47]


In [88]:
#e

vector = np.random.randint(0, 9, size = (3, 3))
vector

array([[3, 3, 3],
       [1, 8, 1],
       [4, 5, 3]])

In [90]:
#f

vector = np.eye(3)
print(vector)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [92]:
#g

vector = np.random.randint(0, 1000, size = (3, 3, 3))
print(vector)

[[[321 713 127]
  [778 711 624]
  [547 450 409]]

 [[604 773 279]
  [967 462 646]
  [943 452  87]]

 [[800 157 151]
  [241 397 694]
  [363 487 216]]]


In [94]:
#h

array = np.random.randint(0, 1000, size = (3, 3, 3))
large = np.max(array)
small = np.min(array)
print(array)
print(f"Largest value: {large}\nSmallest Value: {small}")

[[[633 109 393]
  [650 353 493]
  [728 646 125]]

 [[ 36 517 529]
  [597  90 351]
  [814 250 521]]

 [[103 194 333]
  [924 469  24]
  [399 174 931]]]
Largest value: 931
Smallest Value: 24
